# Generated by Django 5.2.5 on 2026-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='recommended_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
